### ISSUE TITLE
calculate custom score from numerical free responses

### ISSUE THREAD

**Issue by reductionist** [campsych/concerto-platform#116]
Hi, I would like to use free-response answers in a linear test (or questionnaire) in my own scoring formula to arrive at a score.  For example, imagine two items:

1. How old are you? [[Free Response]]
2. What is your current geographic latitude? [[Free Response]]

I would like to use those responses in a formula (so probably via an R-code node) to arrive at a score.  If I understand correctly, responses are stored in a "response_bank" by default, but I don't know how to access those responses so I can use them.  Any suggestions?

Thanks!

Tyler

**Comment by davidstillwell** [comment]
Hi Tyler - you'll need to do a concerto.table.query call to get them using SQL. So in your R code node, start typing conc and then press ctrl + space (I think that's the combination), and then it'll bring up a window that will autocomplete it for you and also bring up help.

In future we'll edit the starter content so that the test/questionnaire nodes have an extra data output with the raw data, so that you can get them from the node rather than doing a DB call.

**Comment by reductionist** [comment]
Hi David, thanks - is there some documentation of what the concerto.table.query() function is looking for as input?  When I type "conc" in the R code node (as in pic) and press Ctrl+Space, nothing happens.

![concerto_r_code_node_conc](https://cloud.githubusercontent.com/assets/26654958/25020632/27cfb0d8-205d-11e7-8dd5-c62e01a414e2.png)

**Comment by przemyslawlis** [comment]
Can you please follow steps below, just to be sure that we're doing it right:
* type **concerto** in the R code from the screenshot above
* make sure that input cursor is right after **concerto**
* press **ctrl** and while holding it pressed also press **space**

This is what you should see after that:
![ac](https://cloud.githubusercontent.com/assets/6590627/25336719/0fe65388-28f9-11e7-9c89-9eb04f34e9be.png)

If you don't see that, can you please check you web console for any potentional errors, and if there are any, can you please paste them here?
How did you install Concerto Platform? Was it installed manually or did you use native Windows installer for it?

**Comment by reductionist** [comment]
Thank you, and sorry for delay - was out of town.  Yes I have confirmed that when I enter "concerto" on that line and press ctrl+space, nothing happens.  Nothing appears in the console, and I installed Concerto using the Windows installer.  I'm using Chrome version 57.0.2987.133 on Windows 7.

**Comment by przemyslawlis** [comment]
Can you please paste the contents of your http://localhost/concerto-platform/bundles/concertopanel/rcache/functionIndex.json file?

**Comment by reductionist** [comment]
Sure:

[{"lib":"acepack","fun":"ace"},{"lib":"acepack","fun":"avas"},{"lib":"Amelia","fun":"amelia"},{"lib":"Amelia","fun":"ameliabind"},{"lib":"Amelia","fun":"compare.density"},{"lib":"Amelia","fun":"disperse"},{"lib":"Amelia","fun":"mi.meld"},{"lib":"Amelia","fun":"missmap"},{"lib":"Amelia","fun":"moPrep"},{"lib":"Amelia","fun":"overimpute"},{"lib":"Amelia","fun":"tscsPlot"},{"lib":"Amelia","fun":"write.amelia"}]

**Comment by przemyslawlis** [comment]
Most probably this issue was related to Windows Installer installation method which is no longer supported. Please check: [docker-compose Installation guide](https://github.com/campsych/concerto-platform/wiki/docker-compose-Installation-guide) for recommended method of installing latest version of Concerto Platform where this should no longer be an issue. Closing.
