### ISSUE TITLE
dbEscapeStrings() - concerto$db$connection is NULL

### ISSUE THREAD

**Issue by AnandGanesh7** [campsych/concerto-platform#117]
Hello, I seem to have the same error message as #62 , however it is slightly different in what causes the null value. This is the error:

> <simpleError in (function (classes, fdef, mtable) { methods <- .findInheritedMethods(classes, fdef, mtable) if (length(methods) == 1L) return(methods[[1L]]) else if (length(methods) == 0L) { cnames <- paste0(""", sapply(classes, as.character), """, collapse = ", ") stop(gettextf("unable to find an inherited method for function %s for signature %s", sQuote(fdef@generic), sQuote(cnames)), domain = NA) } else stop("Internal error in finding inherited methods; didn't return a unique method", domain = NA)})(list("NULL", "character"), structure(function (con, strings, ...) { standardGeneric("dbEscapeStrings")}, generic = structure("dbEscapeStrings", package = "RMySQL"), package = "RMySQL", group = list(), valueClass = character(0), signature = c("con", "strings"), default = \001NULL\001, skeleton = (function (con, strings, ...) stop("invalid call in method dispatch to 'dbEscapeStrings' (no default method)", domain = NA))(con, strings, ...), class = structure("nonstandardGenericFunction", package = "methods")), ): unable to find an inherited method for function ‘dbEscapeStrings’ for signature ‘"NULL", "character"’>

when I run a test. It worked fine on v4 but not on v5. I have the following code and after debugging I found out that concerto$db$connection is NULL! 

![screenshot from 2017-04-12 17-46-11](https://cloud.githubusercontent.com/assets/10592892/24985268/0af13e7e-1fa8-11e7-8a19-adff87099032.png)

Any idea why this is happening? I have setup the MySQL database according to the instructions in the wiki and I'm able to retrieve data in other places as well. Unlike the case before(issue #62 ), my form variables person.info$** are all not NULL (I verified).Hello, I seem to have the same error 

> <simpleError in (function (classes, fdef, mtable) { methods <- .findInheritedMethods(classes, fdef, mtable) if (length(methods) == 1L) return(methods[[1L]]) else if (length(methods) == 0L) { cnames <- paste0(""", sapply(classes, as.character), """, collapse = ", ") stop(gettextf("unable to find an inherited method for function %s for signature %s", sQuote(fdef@generic), sQuote(cnames)), domain = NA) } else stop("Internal error in finding inherited methods; didn't return a unique method", domain = NA)})(list("NULL", "character"), structure(function (con, strings, ...) { standardGeneric("dbEscapeStrings")}, generic = structure("dbEscapeStrings", package = "RMySQL"), package = "RMySQL", group = list(), valueClass = character(0), signature = c("con", "strings"), default = \001NULL\001, skeleton = (function (con, strings, ...) stop("invalid call in method dispatch to 'dbEscapeStrings' (no default method)", domain = NA))(con, strings, ...), class = structure("nonstandardGenericFunction", package = "methods")), ): unable to find an inherited method for function ‘dbEscapeStrings’ for signature ‘"NULL", "character"’>

when I run a test. It worked fine on v4 but not on v5. I have the following code and after debugging I found out that concerto$db$connection is NULL! 

![screenshot from 2017-04-12 17-46-11](https://cloud.githubusercontent.com/assets/10592892/24985268/0af13e7e-1fa8-11e7-8a19-adff87099032.png)

Any idea why this is happening? I have setup the MySQL database according to the instructions in the wiki and I'm able to retrieve data in other places as well. @aboukhary and @przemyslawlis  have you faced a similar situation before? Unlike the case above, my form variables person.info$** are all not NULL (I verified).

**Comment by AnandGanesh7** [comment]
@davidstillwell - do you guys have any idea what this issue might be?

**Comment by AnandGanesh7** [comment]
@davidstillwell @przemyslawlis  - Can I please have your views on this guys?

**Comment by przemyslawlis** [comment]
In your use case, you shouldn't be even caring about the connection resource.
**concerto.table.query** should take care of that for you.

This is how your **concerto.table.query** should look like:

<pre>
concerto.table.query(
  sql = "INSERT INTO `concerto`.`SF36_responses` SET `person_id`='{{person_id}}'",
  params = list(person_id = person.info$assigned_id)
)
</pre>

this way it will automatically replace **{{person_id}}** insert from **sql** argument with its value declared in **params** argument. It also calls **toString** and **dbEscapeStrings** on the value for you.

If you still need to use connection resource, it's now called **concerto$connection**

**Comment by isabelle981** [comment]
@przemyslawlis Thank you for the response! I tried to adopt the code that you suggested but ran into the following problem.

I ran the following codes:

> concerto.table.query(
  sql="INSERT INTO `concerto`.`SF36_responses` SET 
`person_name`='{{fullname}}',
`person_id`='{{assigned_id}}',
`age`='{{age}}',
`sex`='{{sex}}'",
params=list(
fullname=person.info$fullname,
person.info=person.info$assigned_id,
age=person.info$age,
sex=person.info$sex))

But because I have more columns in the `SF36_responses` table than what are referred to in the code, it returned an error: "<simpleError in .local(conn, statement, ...): could not run statement: Field 'q1_id' doesn't have a default value>".  (NOTE: 'q1_id' is the column coming next after 'sex'.)

I have many columns in this table so I don't want to spell them all out in the INSERT statement. Then I tried running either of the following to insert a new row with all default values and then run UPDATE after that.

> concerto.table.query(
  sql="INSERT INTO `concerto`.`SF36_responses` () VALUES ()")

> concerto.table.query(
  sql="INSERT INTO `concerto`.`SF36_responses` DEFAULT VALUES")

Neither worked. The first one returned an error: "<simpleError in .local(conn, statement, ...): could not run statement: Field 'person_name' doesn't have a default value>". (NOTE: 'person_name' is the first column in the table.) The second one returned an error indicating syntax error.

Could you suggest what I can do to here?

Also, I wasn't able to find detailed documentations or sample codes for V5. Would you mind pointing me to any resources? Thank you very much!

@AnandGanesh7
