### ISSUE TITLE
Client workstations

### ISSUE THREAD

**Issue by karends** [campsych/concerto-platform#145]
Can you please advise me of the minimum specification client workstations required to complete a standard Concerto CAT?

???
Processor?
Memory?
Storage?
OS?

**Comment by davidstillwell** [comment]
How do you define "client workstations"? Are you running Concerto locally, via the downloadable package? Or are you running it remotely with a server (e.g. Amazon) and then the client computers are just running it in a browser?

**Comment by karends** [comment]
The latter - Amazon server. Also, do you recommend a specific browser?

**Comment by davidstillwell** [comment]
Requirements on the client workstation are minimal. It's basically the same as browsing a website. Any modern computer with a web browser will have no problem. Normally we test ourselves with Chrome so that's the best browser to use, but any browser should work OK as long as it has JavaScript enabled (which, again, every modern browser does).

**Comment by karends** [comment]
Thank-you, much appreciated.
