### ISSUE TITLE
how can import demos and translated to spanish

### ISSUE THREAD

**Issue by johnfelipe** [campsych/concerto-platform#21]
- Abstract reasoning test

- Quality of life test

- Twilight zone test

and other for build spanish examples?

**Comment by davidstillwell** [comment]
Hi Felipe, we don't share the code for the demos linked on www.concertoplatform.com. We'll be adding other demos in future once we've made some more alterations to the test flow UX on Concerto.  Some of those demos will be available to download. So it's coming, but not quite yet.

**Comment by johnfelipe** [comment]
I can colaborate for create documentacion for each of every test, but i need your help, is possible do a hangout for that?

**Comment by davidstillwell** [comment]
I'd prefer if we leave it a couple of weeks. The reason is that we're changing a couple of things for how to deal with session ID and template definition which will make it easier to do. In the mean time, there's no point creating example tests with documentation because we'll have to update them again.
