### ISSUE TITLE
how can i create more test?

### ISSUE THREAD

**Issue by johnfelipe** [campsych/concerto-platform#23]
Pls tell me how create more test

**Comment by davidstillwell** [comment]
Hi Felipe, what tests do you have in mind?

**Comment by johnfelipe** [comment]
something like patron https://www.jobtestprep.co.uk/images/aptitude/inductive/inductive-reasoning-big-3.png

**Comment by johnfelipe** [comment]
do u view image?

**Comment by davidstillwell** [comment]
That kind of test isn't too difficult. Basically you need to have a linear/CAT test, set the matrix image as the test question, and then the 8 response images as the response options. I teach the creation of such tests in the Concerto courses I run, but I don't have materials that can be shared online because the test items are secret.
