### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by eremiter** [campsych/concerto-platform#248]
### Concerto Platform version
docker 19.03.01
image: campsych/concerto-platform:5.0.beta.7

### Steps to reproduce the issue
use image: campsych/concerto-platform:5.0.beta.7,Open the browser to show connection refused.

use image: campsych/concerto-platform:latest,Open the browser to show connection.

Why are only the latest versions available.

**Comment by przemyslawlis** [comment]
>Why are only the latest versions available.

Since getting out of beta, all releases are tagged and are available as docker images.
See https://github.com/campsych/concerto-platform/wiki/deployment-guide for more info.

>use image: campsych/concerto-platform:5.0.beta.7,Open the browser to show connection refused.
use image: campsych/concerto-platform:latest,Open the browser to show connection.

Please check if all containers started fine by running:
`docker ps`

You can check individual container logs in docker by running:
`docker logs -f container_name`

I'm going to close this issue report since it's for outdated beta version. Please create a new issue report if you have the same issue with any recent stable release.
