### ISSUE TITLE
Cannot control startingTheta in a CAT Assessment Node

### ISSUE THREAD

**Issue by LioChanDaYo** [campsych/concerto-platform#291]
If I try to control a startingTheta in a CAT Assessment Node, be it from a table or a direct input (using an Eval Node), it is never taken into account, and the question selected is always the last of my question table.
If I use as a startingTheta a theta from a return port from another assesment, or from the same assesment, it is correctly taken into account.

**Comment by vesspopov** [comment]
If the startingTheta port on your assessment node is exposed, and set to take value from somewhere prior in your test flow, then it's irrelevant where the value comes from. Hard to say what the problem was without seeing your test flow but an example of how to set it from eval would be:

- eval node with code `startingTheta = 0.1`
- out port on eval node called 'startingTheta'. set to flow variable pointer
- startingTheta in port of assessment node exposed. set to flow variable pointer
- connect assessment node after the eval node
- make sure Order in Items tab of assessment node is set to CAT
