### ISSUE TITLE
Uploading Questions Via CSV

### ISSUE THREAD

**Issue by mtgordon** [campsych/concerto-platform#309]
### Concerto Platform version
5.0.10

### Expected behavior
The theta and sem values to change

### Actual behavior
No change in theta or sem

### Steps to reproduce the issue
I am trying to upload questions using a CSV. I'm guessing that the way I'm entering it is incorrect. I am currently trying the line below for response options. When I view the AssessmentResponses the values for "score" seem to correctly be 0 or 1, but neither of them change the theta or sem values.

{"type":"options","optionsRandomOrder":"1","options":[{"label":"$\\text   {Use a material with a higher modulus of   elasticity.}$","value":"1"},{"label":"$\\text   {Increase the length of the   rod.}$","value":"2"},{"label":"$\\text   {Decrease the radius of the   rod.}$","value":"3"},{"label":"$\\text   {Increase the load.}$","value":"4"}],"defaultScore":"0","scoreMap":[{"value":"1","score":"1","trait":null}]}
--

**Comment by vesspopov** [comment]
Hello. My understanding here is that your problem is not with uploading .csv of questions, but with not seeing a calculation of theta and SEM when you administer the item above in an assessment node. Is that correct? 

I don't see any IRT parameters in this snippet you've shared. If your items have no parameters, it's not possible to calculate theta and SEM since you have no item-level difficulty information. In this case you would just be able to calculate total score (i.e. add up the 1s in this case), which you could then look to transform into a standardised score by reference to previously collected norms.

**Comment by mtgordon** [comment]
Sorry, the full line is below:
2003,3,null,"The uniform bar is constrained to just fit between two fixed supports at temperature $T_1$ and then subjected to a uniform temperature change. Determine the expression of thermal stress (i.e. normal stress) developed in the bar due to the temperature change, and select the correct statement.","{""type"":""options"",""optionsRandomOrder"":""1"",""options"":[{""label"":""20"",""value"":""1""},{""label"":""200"",""value"":""2""},{""label"":""2000"",""value"":""3""}],""defaultScore"":""0"",""scoreMap"":[{""value"":""1"",""score"":""1"",""trait"":null}]}",1,3,0,1

**Comment by vesspopov** [comment]
OK please confirm that you have 'Order' set to CAT on the Items tab of your assessment node, and that you have checked 'Calculate Theta' and 'Calculate SEM' on the Responses tab.. Finally, please list the settings you have in the CAT options tab and I will ask a colleague to help investigate further. Thanks.

**Comment by mtgordon** [comment]
Thanks. I got it to work now.
