### ISSUE TITLE
Is itemBankItems of form flat-item-table?

### ISSUE THREAD

**Issue by snaeil** [campsych/concerto-platform#325]
[In the Wiki](https://github.com/campsych/concerto-platform/wiki/Flat-Item-Table), you describe flat item table attributes:

* id
* fixedIndex
* trait
* question
* p1
* p2
* p3
* p4
* responseLabelN
* responseValueN
* responseScoreN
* responseTraitN
* type
* skippable
* instructions

When exposing `itemBankItems` from the assessment node, an example can be seen from the default value:
```json
[
{"id":1,"question":"10 + 10","responseOptions":{"type":"options","optionsRandomOrder":"1","options":[{"label":"20","value":"1","fixedIndex":null},{"label":"200","value":"2","fixedIndex":null},{"label":"2000","value":"3","fixedIndex":null}],"painMannequinGender":"female","painMannequinGenderValue":"male","defaultScore":"0","scoreMap":[{"value":"1","score":"1","trait":null}],"gracelyScaleShow":"","painMannequinAreaMultiMarks":"1","optionsColumnsNum":null},"fixedIndex":"","p1":"0","p2":"0","p3":"0","p4":"0","p5":"0","p6":"0","p7":"0","p8":"0","p9":"0","trait":"math","skippable":"0","instructions":""},
{"id":2,"question":"100 + 100","responseOptions":{"type":"options","optionsRandomOrder":"1","options":[{"label":"20","value":"1","fixedIndex":null},{"label":"200","value":"2","fixedIndex":null},{"label":"2000","value":"3","fixedIndex":null}],"painMannequinGender":"female","painMannequinGenderValue":"male","defaultScore":"0","scoreMap":[{"value":"2","score":"1","trait":null}],"gracelyScaleShow":"","painMannequinAreaMultiMarks":"1","optionsColumnsNum":null},"fixedIndex":"","p1":"0","p2":"0","p3":"0","p4":"0","p5":"0","p6":"0","p7":"0","p8":"0","p9":"0","trait":"math","skippable":"0","instructions":""},
{"id":3,"question":"1000 + 1000","responseOptions":{"type":"options","optionsRandomOrder":"1","options":[{"label":"20","value":"1","fixedIndex":null},{"label":"200","value":"2","fixedIndex":null},{"label":"2000","value":"3","fixedIndex":null}],"painMannequinGender":"female","painMannequinGenderValue":"male","defaultScore":"0","scoreMap":[{"value":"3","score":"1","trait":null}],"gracelyScaleShow":"","painMannequinAreaMultiMarks":"1","optionsColumnsNum":null},"fixedIndex":"","p1":"0","p2":"0","p3":"0","p4":"0","p5":"0","p6":"0","p7":"0","p8":"0","p9":"0","trait":"math","skippable":"0","instructions":""}
]
```

My question is now whether a flat-item-table is expected for the attribute `itemBankItems`.  
**If yes** , are p5-p9 the same as `[responseLabelN, responseValueN, responseScoreN, responseTraitN, type]`?

**Comment by vesspopov** [comment]
Hi Snaeil, the default value of itemBankItems you've pasted is not in flat table format since the 'response options' variable is in JSON and has scoremap. I therefore think this input port can't take a flat item table as input. If you are using flat table to store your items then you should set flat table type in your assessment node, so that it converts the table to the format required.

p5-p9 are optional parameter fields which should contain IRT parameters. They are completely optional and would only be used with certain IRT models (for example you might have 10 response options to a question and 9 threshold values). All parameter fields are optional and nullable. These fields are not the same as responseLabel, responseValue, etc. and the other fields you have listed.
