### ISSUE TITLE
Add plots to feedback page

### ISSUE THREAD

**Issue by mizumot** [campsych/concerto-platform#329]
### Concerto Platform version
v5.0.22

### Expected behavior
In the feedback page (i.e., showPage), I would like to show plots created with R depending on the user's test result.

### Actual behavior
Cannot show a plot created in another node. 

### Steps to reproduce the issue
This manual suggests "Visualizing the new values in some way". I would like to know how I can do it. 
https://github.com/campsych/concerto-platform/blob/master/wiki/Adding%20Feedback.pdf

I would appreciate it if you give me some advice.

**Comment by mizumot** [comment]
Solved by directly referring to the file. Is there a better way?

In eval:
png(filename="/data/files/rplot.png")
plot(something)
dev.off()

In Content - HTML:
<img src="/files/rplot.png" />

With the Version 4 of Concerto, I was able to do the same with codes because it was described in the manual. It took me a long time to figure it out with Version 5. It is partly because the documentation is not thorough (compared with the one for Version 4). I hope the development team can provide a more detailed explanation to users like me.

**Comment by vesspopov** [comment]
Hi, thanks for the feedback. There are many ways in which you might want to show scores, so it depends on the test and we can't very easily document all of the options. Concerto 4 test creation was all R code-based, so you would need to generate charts in R using something like ggplot2. You can still do that in Concerto 5, but it's rather inefficient.

The alternative approach is to pass your calculated scores as an R object to a showPage node, make this object available in Javascript scope (i.e. testRunner.R.controller.whateverobject), and then generate you charts in HTML/JS. This approach does require some web development knowledge, as opposed to R knowledge. To document this fully we'd need to provide an example feedback template for a given type of score visualisation (e.g. percentiles). That's definitely something we can consider making available to the community, but it won't cover all the feedback use cases because Concerto operates on a lower level (i.e. your feedback page can be any HTML whatsoever, and we don't provide - nor limit you to - pre-built feedback blocks).

We've also thought about having a node that visualises data, as an extension of the scoring node. Probably that would not come til Concerto 6 as it entails a rework of the front-end libraries used by the platform.
