### ISSUE TITLE
what is progress?

### ISSUE THREAD

**Issue by johnfelipe** [campsych/concerto-platform#33]
Hi, im back i hope translate all to spanish very soon, but tell me, what about progress for create test more complex?
Tnks

**Comment by davidstillwell** [comment]
We have a new test node called polyCAT which does polytomous CAT. Also a new user-created node called Aurei that does emotional testing. We've also made many changes to the test creation procedure, so that session variable is not necessary to pass any more, as well as template_def.

Check wiki page to see what's there: https://github.com/campsych/concerto-platform/wiki
