### ISSUE TITLE
Simple user guide to create the first test

### ISSUE THREAD

**Issue by luismulinari** [campsych/concerto-platform#4]
Hello everyone.

I am Concerto 4 user and I am really excited about Concerto 5. I have installed the new version on my computer (I created a docker to improve the installation process. I can share it with you if you want), but I  did not understand the new method to create a test. Can you share with me a "Test example" or create a simple documentation to create a first test?

I am a Symfony Developer and, if you want, I think that I can contribute with the project.

Best regards,
Luis Henrique Mulinari

**Comment by przemyslawlis** [comment]
Hi Luis,

Nice to hear that! Currently our documentation is lacking but this will be changed in close future. You should be able to create R code based test much the same way as in v4.
Any contribution is much  appreciated. Feel free to submit pull request whenever you want. Translation to other languages would also be very welcomed.
Yes, I would like to take a look at your docker, as this is something we are considering to add.

**Comment by davidstillwell** [comment]
Hi Luis, sorry our documentation is lacking at the moment! We know it needs doing. Our plan is to have a few videos for general overviews of common topics, and then the wiki will contain more detailed instructions for specific issues. So far this is what our videos look like... we're still going to improve them but they're good enough to show a couple of simple tests to start with:

https://www.youtube.com/watch?v=qe_5Hh2ShOU - Create a questionnaire
https://www.youtube.com/watch?v=boFAkQcaoag - Create a CAT test

For both videos I highly recommend running in HD. You might also need to turn the volume up because I'm still learning how to do it well!

**Comment by przemyslawlis** [comment]
No response for over 20 days - closing.
