### ISSUE TITLE
How to save the scores of a Questionnaire?

### ISSUE THREAD

**Issue by tangi75** [campsych/concerto-platform#44]
Hi,

I successfully managed to save the userId passed in the URL using the Save Data node as explained in https://github.com/campsych/concerto-platform/wiki/Passing-URL-parameters

I'm also able to compute a MBTI-like profile by following your guideline in https://github.com/campsych/concerto-platform/issues/41

I would now like to save the scores into default_data_table.
I tried to connect the scores output of the Questionnaire node to the new_data input of another Save Data node using "list(scores=scores)", the scores output being thus connected to two nodes (Info and Save Data), but nothing get saved.

How may I save the scores of a Questionnaire and still display it?

**Comment by davidstillwell** [comment]
Congrats, it sounds like you're doing some neat stuff.

You shouldn't have any issues connecting a data output to two data inputs. Perhaps the issue is that the scores output is already a list, so you can probably just connect scores directly without doing the list(scores=scores) transform.

We are considering changing the colours of the inputs/outputs depending on what data type a node is. This should make it easier in future to tell that the scores output is a list already.

Please let me know if it works so I can close this.

**Comment by tangi75** [comment]
I tried various things in the Questionnaire-scores to Save_data-new_data link : 
- list(scores=scores)
- scores$profile = paste(ifelse(scores$IE < 0, "I", "E"), ifelse(scores$SN < 0, "S", "N"), ifelse(scores$FT < 0, "F", "T"), ifelse(scores$JP < 0, "J", "P"), sep="")
list(mbti=scores$profile)
- scores=scores

I get no error (even in the javascript console in debug) but nothing get into the database.

**Comment by tangi75** [comment]
Here is my test flow to make it clear:
![image](https://cloud.githubusercontent.com/assets/21256944/18756036/ab520776-80ee-11e6-8123-a7d426af37cc.png)

**Comment by davidstillwell** [comment]
Ah, the problem is that the save_data node needs to be part of the flow, otherwise it never gets called. So you'll need to connect the in/out connections - you can connect it between questionnaire_v2 and info_v2. So your execution flow will be:
1. Run questionnaire
2. Store results
3. Show info page

**Comment by tangi75** [comment]
Thanks a lot for your fast support!

**Comment by tangi75** [comment]
With the following test flow, I get the scores saved correctly:
![image](https://cloud.githubusercontent.com/assets/21256944/18762573/9857fb60-8109-11e6-82f7-e5e4328a8e7b.png)
They nevertheless aren't passed along to the Info node. I tried to add a link between save_data/data_bank and info/inserts with various values without success.
How to pass scores from the save_data node to the info node?

**Comment by davidstillwell** [comment]
Make another connection from questionnaire_v2|scores to info_v2|inserts - i.e. you can use the same output node twice.

**Comment by tangi75** [comment]
It works perfectely! Thank you David.

**Comment by tangi75** [comment]
Hello David,

Here is a tutorial I wrote based on what I learned from implementing this test flow:

[Test flow tutorial.md.txt](https://github.com/campsych/concerto-platform/files/558733/Test.flow.tutorial.md.txt)

I tried to create a pull request on the wiki repo (having added this new file on a new branch) but I obviously don't have the required rights to do so.
