### ISSUE TITLE
Custom Insertion of Form Data into Tables

### ISSUE THREAD

**Issue by aboukhary** [campsych/concerto-platform#64]
I am new to Concerto v5, and I wonder what would be the best practice to insert a custom form output into a custom table.

**Comment by przemyslawlis** [comment]
Use **save_data** node to save the data from form:

![save_data](https://cloud.githubusercontent.com/assets/6590627/20218522/4b259ac6-a825-11e6-8c79-a4a0b80388d8.png)

**Comment by JanowskiMaciej** [comment]
And what now? The data from the form does not go to the table with questionnaire answers (e.g. to default_questionnaire_response_table) but to another table (e.g. default_data_table). Is it possible to have them in one table?

**Comment by davidstillwell** [comment]
Save data node expects the column headings that are in the default_data_table. You could add extra columns to the default_questionnaire_response_table to match those from default_data_table (make sure that the data types are correct too). In this case, if you tell save_data node to store in default_questionnaire_response_table then it should all be in one table.

But really, it shouldn't be a problem to have two separate tables, because you can just merge them together using session_id.

**Comment by JanowskiMaciej** [comment]
The problem is that when I try to use the modified table there is no data from the form that Concerto could write in the question_id column and I have the error message:
Error in .local(conn, statement): could not run statement: Field 'question_id' doesn't have a default value.

**Comment by davidstillwell** [comment]
Hm, sounds like the MySQL table is set up so that it expects a value.

Your alternative is to either:
1. if you have access to the MySQL table directly, then change it so that it accepts empty values
2. create a completely new table that has all of the fields that both tables expect, and then point both nodes at the new table. Because you've created the new table yourself from the Concerto system, then there won't be any MySQL requirements to have non-empty values.

Really though - both answers are something of a "hack." As I said before, the two types of data collected by questionnaire node and forms node are different, so it expects them to be in different tables. The best way is to keep the two separate tables, and then download both and merge them together when you're doing an analysis.
