### ISSUE TITLE
Installation Linux

### ISSUE THREAD

**Issue by fthamura** [campsych/concerto-platform#71]
why dont we have the apt for all the php, mysql, r etc?

so we can just follow the step .

esp the mysql dev for r package

https://github.com/campsych/concerto-platform/wiki/Linux-installation

**Comment by przemyslawlis** [comment]
That would be great. Would you be willing to create it?

**Comment by aboukhary** [comment]
This is the apt-get list I fetched for Debian 8.6 installation
apt-get install -y apache2 mysql-server git npm php5 php-pear php5-mysql php5-curl r-base libmysqlclient-dev r-cran-ggplot2 r-cran-plyr r-cran-reshape2

* I am not sure whether php5-curl and php-pear are required. 
** Since R core in Debian is version 3.1, I got some R packages from CRAN while others from Debian Repo.

**Comment by przemyslawlis** [comment]
If you mean just a list of apt packages that should be installed, here's the list from Ubuntu 16.04 (for Apache as web server and MySQL as database):

> apt-get -y install mysql-server libmysqlclient-dev apache2 r-base r-base-dev git curl npm libapache2-mod-php7.0 php7.0 php7.0-mysql php-xml

@fthamura: yes, you're right this should be part of installation wiki. I'll update it soon and comment back  here when it's done.

**Comment by przemyslawlis** [comment]
Installation guide is now updated. See: https://github.com/campsych/concerto-platform/wiki/Linux-installation
