### ISSUE TITLE
Compatibility Problem between Releases 160 and 171

### ISSUE THREAD

**Issue by aboukhary** [campsych/concerto-platform#83]
v5.0.beta.2.171 refuses to upload nodes created in v5.0.beta.2.160 release, which hinders content development, will this change in the future?

**Comment by przemyslawlis** [comment]
v5.0.beta.2.168 (if I remember correctly) introduced a change in export file structure format.
Update your Concerto Platform to at least version above and reexport your content. You'll then be able to import it to any other Concerto Platform with version above v5.0.beta.2.168.

We're doing what we can to minimise amount of changes like that (this is the first one in since public release of v5), but unfortunately we need to accept that it will happen from time to time.
